persistence:
  enabled: true
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
    ingress.kubernetes.io/auth-type: "forward"
    ingress.kubernetes.io/auth-url: "http://auth0-forwardauth.default.svc.cluster.local/authorize"
    ingress.kubernetes.io/auth-trust-headers: "true"
timezone: "America/New_York"
keel:
  policy: "glob:*.*.*-v8"
  trigger: poll
  pollSchedule: "@every 1h"
  approvals: 1
  images:
    - repository: image.repository
      tag: image.tag
