apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-backup-restic-pv
spec:
  storageClassName: data
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.7.7
    path: "/tank/backups/restic"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-backup-restic-pv
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: data
  resources:
    requests:
      storage: 1Mi