apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-audiobooks-pv
spec:
  storageClassName: media-audiobooks
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 10.0.7.7
    path: "/tank/media/itunes/Audiobooks"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-audiobooks-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-audiobooks
  resources:
    requests:
      storage: 1Mi