image:
  repository: k8s.gcr.io/heapster-amd64
  tag: v1.5.4
rbac:
  create: true
keel:
  policy: all
  trigger: poll
  pollSchedule: "@every 1h"
  images:
    - repository: image.repository
      tag: image.tag