ImageTag: "1.4.0"
uiIngress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
    ingress.kubernetes.io/auth-type: "forward"
    ingress.kubernetes.io/auth-url: "http://auth0-forwardauth.default.svc.cluster.local/authorize"
    ingress.kubernetes.io/auth-trust-headers: "true"
keel:
  policy: all
  trigger: poll
  pollSchedule: "@every 1h"
  approvals: 1
  images:
    - repository: Image
      tag: ImageTag
