apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: stash-consul
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: consul-consul
  fileGroups:
  - path: /var/lib/consul
    retentionPolicyName: 'keep-last-5'
  backend:
    local:
      mountPath: /mnt/backup/
      persistentVolumeClaim:
          claimName: nfs-backup-restic-pv-10g-kube-system
    storageSecretName: restic-secret
  schedule: '@daily'
  volumeMounts:
  - mountPath: /var/lib/consul
    name: datadir
  retentionPolicies:
  - name: 'keep-last-5'
    keepLast: 5
    prune: true
