apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: stash-deluge
  namespace: default
spec:
  selector:
    matchLabels:
      app: deluge
  fileGroups:
  - path: /config
    retentionPolicyName: 'keep-last-5'
  backend:
    local:
      mountPath: /mnt/backup/
      persistentVolumeClaim:
          claimName: nfs-backup-restic-pv-10g
    storageSecretName: restic-secret
  schedule: '@daily'
  volumeMounts:
  - mountPath: /config
    name: config
  retentionPolicies:
  - name: 'keep-last-5'
    keepLast: 5
    prune: true