master:
  persistence:
    storageClass: "rbd"
data:
  persistence:
    storageClass: "rbd"
keel:
  policy: minor
  trigger: poll
  pollSchedule: "@every 1h"
  images:
    - repository: image.repository
      tag: image.tag
