kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rbd
provisioner: ceph.com/rbd
parameters:
  monitors: 10.0.10.7:6789,10.0.10.9:6789,10.0.10.14:6789
  pool: kube
  adminId: admin
  adminSecretNamespace: default
  adminSecretName: ceph-admin-secret
  userId: kube
  userSecretNamespace: default
  userSecretName: ceph-secret
  imageFormat: "2"
  imageFeatures: layering