apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: stash-wordpress
  namespace: default
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  fileGroups:
  - path: /var/www/html
    retentionPolicyName: 'keep-last-5'
  backend:
    local:
      mountPath: /mnt/backup/
      persistentVolumeClaim:
          claimName: nfs-backup-restic-pv
    storageSecretName: restic-secret
  schedule: '@every 5m'
  volumeMounts:
  - mountPath: /var/www/html
    name: wordpress-persistent-storage
  retentionPolicies:
  - name: 'keep-last-5'
    keepLast: 5
    prune: true
