apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: external-proxmox-nd
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/auth-type: "forward"
    ingress.kubernetes.io/auth-url: "http://auth0-forwardauth.default.svc.cluster.local/authorize"
    ingress.kubernetes.io/auth-trust-headers: "true"
spec:
  rules:
  - host: proxmox.nd.$DOMAIN
    http:
      paths:
      - backend:
          serviceName: external-proxmox-nd
          servicePort: 19999
---
apiVersion: v1
kind: Service
metadata:
  name: external-proxmox-nd
spec:
  ports:
  - name: http
    port: 19999
  type: ExternalName
  externalName: proxmox