image:
  tag: 5.9.29
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 20Gi
timezone: "America/New_York"
runAsRoot: false
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
controllerService:
  type: LoadBalancer
  loadBalancerIP: 10.0.7.82
stunService:
  type: LoadBalancer
  loadBalancerIP: 10.0.7.83
discoveryService:
  type: LoadBalancer
  loadBalancerIP: 10.0.7.84
keel:
  policy: all
  trigger: poll
  pollSchedule: "@every 1h"
  images:
    - repository: image.repository
      tag: image.tag
